/**
 * Multiple Choice Questions: "Dracula" by Bram Stoker
 * Source: Project Gutenberg (gutenberg.org) - Book #345
 * Generated by Papersaurus AI Educational Tools
 * 
 * Each question has 5 options (A-E) with exactly one correct answer.
 * See answers.js for detailed explanations of all options.
 */

const questions = [
  {
    "id": 1,
    "question": "In what year was Bram Stoker's 'Dracula' first published?",
    "options": {
      "A": "1887",
      "B": "1893",
      "C": "1897",
      "D": "1901",
      "E": "1885"
    },
    "correctAnswer": "C"
  },
  {
    "id": 2,
    "question": "What narrative technique does Stoker primarily use to tell the story of 'Dracula'?",
    "options": {
      "A": "Third-person omniscient narration",
      "B": "First-person narration from Dracula's perspective",
      "C": "Epistolary format using journal entries, letters, and newspaper clippings",
      "D": "Second-person narration addressing the reader directly",
      "E": "Stream-of-consciousness narration"
    },
    "correctAnswer": "C"
  },
  {
    "id": 3,
    "question": "Which character travels to Transylvania at the beginning of the novel to assist Count Dracula with a real estate transaction?",
    "options": {
      "A": "Dr. Abraham Van Helsing",
      "B": "Arthur Holmwood",
      "C": "Quincey Morris",
      "D": "Jonathan Harker",
      "E": "Dr. John Seward"
    },
    "correctAnswer": "D"
  },
  {
    "id": 4,
    "question": "Who is the Dutch professor and vampire expert who leads the group of heroes against Dracula?",
    "options": {
      "A": "Dr. John Seward",
      "B": "Professor Abraham Van Helsing",
      "C": "Professor Moriarty",
      "D": "Dr. Hennessey",
      "E": "Renfield"
    },
    "correctAnswer": "B"
  },
  {
    "id": 5,
    "question": "What is the primary literary genre classification of 'Dracula'?",
    "options": {
      "A": "Romantic comedy",
      "B": "Science fiction",
      "C": "Gothic horror",
      "D": "Historical realism",
      "E": "Pastoral fiction"
    },
    "correctAnswer": "C"
  },
  {
    "id": 6,
    "question": "Which character is a patient in Dr. Seward's asylum who eats insects and small animals, believing he can absorb their life force?",
    "options": {
      "A": "Jonathan Harker",
      "B": "Quincey Morris",
      "C": "Arthur Holmwood",
      "D": "Renfield",
      "E": "Peter Hawkins"
    },
    "correctAnswer": "D"
  },
  {
    "id": 7,
    "question": "Which Victorian-era themes have scholars frequently examined in relation to 'Dracula'?",
    "options": {
      "A": "Industrialization and labor unions exclusively",
      "B": "Race, religion, gender, and sexuality",
      "C": "Maritime trade and colonialism exclusively",
      "D": "Democratic reform and suffrage exclusively",
      "E": "Agricultural practices and land ownership"
    },
    "correctAnswer": "B"
  },
  {
    "id": 8,
    "question": "Which female character becomes one of Dracula's victims and is eventually staked by the heroes after becoming a vampire?",
    "options": {
      "A": "Mina Harker",
      "B": "Mrs. Westenra",
      "C": "Lucy Westenra",
      "D": "The Brides of Dracula",
      "E": "Sister Agatha"
    },
    "correctAnswer": "C"
  },
  {
    "id": 9,
    "question": "What circumstance led to 'Dracula' entering the public domain in the United States, enabling countless adaptations?",
    "options": {
      "A": "Stoker voluntarily released his copyright",
      "B": "The copyright expired after the standard 50-year term",
      "C": "A court ruling invalidated all Gothic fiction copyrights",
      "D": "Stoker incorrectly filed the U.S. copyright paperwork",
      "E": "Stoker's estate sold the rights to the public"
    },
    "correctAnswer": "D"
  },
  {
    "id": 10,
    "question": "According to the Guinness Book of World Records, what distinction does Count Dracula hold in popular culture?",
    "options": {
      "A": "Best-selling fictional character of all time",
      "B": "Most portrayed literary character in film and television with over 700 appearances",
      "C": "Most translated literary character in history",
      "D": "First fictional character to appear in a motion picture",
      "E": "Most banned literary character in schools worldwide"
    },
    "correctAnswer": "B"
  }
];

module.exports = { questions };
